metadata:
  name: {{cookiecutter.prj_name}}{% if cookiecutter.use_image == "y" %}
  image: {{cookiecutter.image_org}}/{{cookiecutter.prj_name}}{% endif %}{% if cookiecutter.use_codegen == "y" %}
  apifile: api.yml{% endif %}
  version: {{cookiecutter.version}}
  pretag: dev
  versioned:
  - filename: pom.xml
    search: ^  <version>${VERSION}</version>
    replace: '  <version>${NEXT_VERSION}</version>'{% if cookiecutter.use_codegen == "y" %}
  - filename: api.yml
    search: 'version: "${VERSION}"'
    replace: 'version: "${NEXT_VERSION}"'{% endif %}
